"""Generate src/pokemon_agent/games/pokemon_red/battle_data.py from the pokered disassembly:
move type/power/accuracy/PP (data/moves/moves.asm, in move-id order) and the Gen 1 type chart
(data/types/type_matchups.asm, incl. its quirks). Deterministic; re-run to refresh.

  uv run python scripts/gen_battle_data.py
"""
from __future__ import annotations

import os
import re
from pathlib import Path

POKERED = Path(os.environ.get("POKERED", "/tmp/pokered"))
OUT = Path(__file__).resolve().parent.parent / "src" / "pokemon_agent" / "games" / "pokemon_red" / "battle_data.py"
MULT = {"SUPER_EFFECTIVE": 2.0, "NOT_VERY_EFFECTIVE": 0.5, "NO_EFFECT": 0.0}


def main() -> None:
    types = {}
    for m in re.finditer(r"const\s+(\w+)\s*;\s*\$([0-9A-Fa-f]+)", (POKERED / "constants/type_constants.asm").read_text()):
        types[int(m.group(2), 16)] = m.group(1).replace("_TYPE", "")
    moves = {}
    text = (POKERED / "data/moves/moves.asm").read_text().split("Moves:", 1)[1]
    for i, m in enumerate(re.finditer(r"^\s*move\s+(\w+),\s*\w+,\s*(\d+),\s*(\w+),\s*(\d+),\s*(\d+)", text, re.M), 1):
        moves[i] = (m.group(1), m.group(3).replace("_TYPE", ""), int(m.group(2)), int(m.group(4)), int(m.group(5)))
    effects = {}
    for m in re.finditer(r"db\s+(\w+),\s*(\w+),\s*(SUPER_EFFECTIVE|NOT_VERY_EFFECTIVE|NO_EFFECT)",
                         (POKERED / "data/types/type_matchups.asm").read_text()):
        effects[(m.group(1).replace("_TYPE", ""), m.group(2).replace("_TYPE", ""))] = MULT[m.group(3)]
    lines = ['"""GENERATED by scripts/gen_battle_data.py from pokered — do not edit by hand."""', "",
             "# type id -> name", f"TYPE_NAMES = {types!r}", "",
             "# move id -> (CONST, type, power, accuracy %, max PP)", "MOVE_DATA = {"]
    lines += [f"    {k}: {v!r}," for k, v in sorted(moves.items())]
    lines += ["}", "", "# (attacking type, defending type) -> multiplier (anything absent = 1.0)", "TYPE_EFFECTS = {"]
    lines += [f"    {k!r}: {v}," for k, v in sorted(effects.items())]
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {len(moves)} moves, {len(types)} types, {len(effects)} matchups")


if __name__ == "__main__":
    main()
